# Backend Dev
FROM rust:1.93.0-bookworm AS backend
WORKDIR /app
# Install cargo-watch for hot reloading
RUN cargo install cargo-watch
# The source code will be mounted by docker-compose

# Frontend Dev
FROM oven/bun:1.3.8-debian AS frontend
WORKDIR /app/web
# The source code will be mounted by docker-compose
