services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./data:/app/data
    environment:
      - RUST_LOG=info
      - WEBAUTHN_RP_ID=schlift.com
      - WEBAUTHN_RP_ORIGIN=https://app.schlift.com
      - WEBAUTHN_ANDROID_ORIGIN=android:apk-key-hash:Hwxr_adafRh6rlMbMzDNEX8x9QWOBakh_yOw6HTCIew
      - WEBAUTHN_ANDROID_ORIGINS=android:apk-key-hash:oX5Jnmwq_UQ8_8dpupoKwQlGNOmMSUbcVSLLHh-lwsg,android:apk-key-hash:Hwxr_adafRh6rlMbMzDNEX8x9QWOBakh_yOw6HTCIew,android:apk-key-hash:_AqWk4iSMELh5t8IwmPW1iGNdIAfVV3D6wThyTRJGgk
      - ANDROID_CERT_SHA256=A1:7E:49:9E:6C:2A:FD:44:3C:FF:C7:69:BA:9A:0A:C1:09:46:34:E9:8C:49:46:DC:55:22:CB:1E:1F:A5:C2:C8
    expose:
      - "50051"
    networks:
      - home_default

# note this connects to the network set up by caddy in the home assist project
networks:
  home_default:
    external: true
