#!/usr/bin/env node
// Builds docs/regime-explorer.html from testdata/regime_timelines.json.
//
// The timelines are generated by the Rust regime state machines
// (`LIFT_SNAPSHOT_TIMELINE=1 cargo test regime_timeline`), so the page shows
// exactly what the app would prescribe — there is no second implementation of
// the progression rules to drift out of sync.
//
// Usage:
//   LIFT_SNAPSHOT_TIMELINE=1 cargo test regime_timeline   # refresh the data
//   node scripts/build_regime_explorer.mjs                # rebuild the page

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const fixture = JSON.parse(
  readFileSync(join(root, 'testdata/regime_timelines.json'), 'utf8'),
);

const SCENARIO_META = {
  steady_progress: {
    label: 'Everything on target',
    blurb: 'Three sessions a week, every prescribed set completed.',
  },
  occasional_misses: {
    label: 'Occasional missed session',
    blurb: 'Mostly on target, falling short roughly every fifth session.',
  },
  stalling_out: {
    label: 'Stalling out',
    blurb:
      'Progress, then repeated misses — shows the stall counter and the deload it triggers.',
  },
  comeback_after_layoff: {
    label: 'Six weeks off',
    blurb:
      'Training normally, then a 45-day break, then straight back in. The layoff deload.',
  },
  two_layoffs: {
    label: 'Two breaks',
    blurb:
      'A 16-day break lands in the 90% band; a 60-day break lands in the 80% band.',
  },
};

const SEED_LABEL = {
  default: 'Starting from scratch',
  novice: 'Novice',
  intermediate: 'Intermediate',
};

// Round to keep the inlined payload small; every weight is a 2.5 lb multiple.
const r = (n) => Math.round(n * 10) / 10;

function compactSession(s) {
  return {
    d: s.day,
    g: s.days_since_previous,
    n: s.workout_name,
    dl: s.deloaded ? 1 : 0,
    hit: s.result === 'hit' ? 1 : 0,
    x: s.exercises.map((e) => ({
      e: e.exercise,
      t: e.tier || '',
      s: e.sets.map((set) => ({
        w: r(set.weight),
        r: set.reps,
        c: set.count,
        a: set.is_amrap ? 1 : 0,
      })),
    })),
  };
}

const data = { regimes: {} };
for (const [key, regime] of Object.entries(fixture.regimes)) {
  const seeds = {};
  for (const [seedKey, seed] of Object.entries(regime.seeds)) {
    const scenarios = {};
    for (const [scenKey, sessions] of Object.entries(seed.scenarios)) {
      scenarios[scenKey] = sessions.map(compactSession);
    }
    seeds[seedKey] = {
      label: SEED_LABEL[seedKey] ?? seedKey,
      start: Object.fromEntries(
        Object.entries(seed.initial_weights).map(([k, v]) => [k, r(v)]),
      ),
      scenarios,
    };
  }
  data.regimes[key] = { name: regime.display_name, seeds };
}
data.scenarioMeta = SCENARIO_META;

const payload = JSON.stringify(data);

const html = String.raw`<title>How Schlift progresses your lifts</title>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<style>
  :root {
    color-scheme: light dark;

    /* Calibrated plate colours — the standard IPF weights, used semantically:
       red for a missed session, green for progression, yellow for a deload. */
    --plate-red: #c8362f;
    --plate-blue: #2b5fa8;
    --plate-yellow: #d9a521;
    --plate-green: #2e7d4f;

    --ground: #fafaf9;
    --panel: #ffffff;
    --panel-2: #f2f3f4;
    --ink: #14171a;
    --ink-2: #4a5157;
    --ink-3: #767f87;
    --rule: #dfe2e5;
    --rule-strong: #c3c9cf;
    --accent: var(--plate-red);
    --shadow: 0 1px 2px rgb(20 23 26 / 0.06), 0 8px 24px -12px rgb(20 23 26 / 0.18);

    --mono: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas,
      "Liberation Mono", monospace;
    --sans: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue",
      Arial, sans-serif;
  }

  @media (prefers-color-scheme: dark) {
    :root {
      --ground: #15181c;
      --panel: #1c2025;
      --panel-2: #23282e;
      --ink: #eef1f3;
      --ink-2: #b0b8c0;
      --ink-3: #7f8892;
      --rule: #2c323a;
      --rule-strong: #3b434c;
      --accent: #e8574d;
      --plate-green: #48a875;
      --plate-yellow: #e5b73f;
      --plate-blue: #5b8fd6;
      --shadow: 0 1px 2px rgb(0 0 0 / 0.4), 0 8px 24px -12px rgb(0 0 0 / 0.7);
    }
  }

  :root[data-theme="dark"] {
    --ground: #15181c;
    --panel: #1c2025;
    --panel-2: #23282e;
    --ink: #eef1f3;
    --ink-2: #b0b8c0;
    --ink-3: #7f8892;
    --rule: #2c323a;
    --rule-strong: #3b434c;
    --accent: #e8574d;
    --plate-green: #48a875;
    --plate-yellow: #e5b73f;
    --plate-blue: #5b8fd6;
    --shadow: 0 1px 2px rgb(0 0 0 / 0.4), 0 8px 24px -12px rgb(0 0 0 / 0.7);
  }

  :root[data-theme="light"] {
    --ground: #fafaf9;
    --panel: #ffffff;
    --panel-2: #f2f3f4;
    --ink: #14171a;
    --ink-2: #4a5157;
    --ink-3: #767f87;
    --rule: #dfe2e5;
    --rule-strong: #c3c9cf;
    --accent: #c8362f;
    --plate-green: #2e7d4f;
    --plate-yellow: #d9a521;
    --plate-blue: #2b5fa8;
    --shadow: 0 1px 2px rgb(20 23 26 / 0.06), 0 8px 24px -12px rgb(20 23 26 / 0.18);
  }

  * { box-sizing: border-box; }

  body {
    margin: 0;
    background: var(--ground);
    color: var(--ink);
    font-family: var(--sans);
    line-height: 1.5;
    -webkit-font-smoothing: antialiased;
  }

  .wrap {
    max-width: 1080px;
    margin: 0 auto;
    padding: clamp(1.5rem, 4vw, 3rem) clamp(1rem, 4vw, 2rem) 5rem;
    display: flex;
    flex-direction: column;
    gap: 2rem;
  }

  header { display: flex; flex-direction: column; gap: 0.75rem; }

  .eyebrow {
    font-family: var(--mono);
    font-size: 0.7rem;
    letter-spacing: 0.14em;
    text-transform: uppercase;
    color: var(--ink-3);
  }

  h1 {
    margin: 0;
    font-size: clamp(1.8rem, 4.5vw, 2.9rem);
    font-weight: 800;
    letter-spacing: -0.025em;
    line-height: 1.05;
    text-wrap: balance;
  }

  .lede {
    margin: 0;
    max-width: 62ch;
    font-size: 1.05rem;
    color: var(--ink-2);
  }

  .panel {
    background: var(--panel);
    border: 1px solid var(--rule);
    border-radius: 6px;
    box-shadow: var(--shadow);
  }

  /* ---- controls ---- */
  .controls {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(210px, 1fr));
    gap: 1px;
    background: var(--rule);
    overflow: hidden;
  }
  .field {
    background: var(--panel);
    padding: 0.9rem 1rem 1rem;
    display: flex;
    flex-direction: column;
    gap: 0.45rem;
  }
  .field > label {
    font-family: var(--mono);
    font-size: 0.66rem;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--ink-3);
  }
  select {
    width: 100%;
    font: inherit;
    font-size: 0.92rem;
    color: var(--ink);
    background: var(--panel-2);
    border: 1px solid var(--rule-strong);
    border-radius: 4px;
    padding: 0.45rem 0.55rem;
  }
  select:focus-visible {
    outline: 2px solid var(--accent);
    outline-offset: 1px;
  }

  .scenario-note {
    padding: 0.85rem 1rem;
    border-top: 1px solid var(--rule);
    color: var(--ink-2);
    font-size: 0.9rem;
    background: var(--panel);
  }

  /* ---- chart ---- */
  .chart-head {
    display: flex;
    flex-wrap: wrap;
    align-items: baseline;
    justify-content: space-between;
    gap: 0.75rem;
    padding: 1rem 1.15rem 0;
  }
  h2 {
    margin: 0;
    font-size: 1rem;
    font-weight: 700;
    letter-spacing: -0.01em;
  }
  .legend {
    display: flex;
    flex-wrap: wrap;
    gap: 0.85rem;
    font-size: 0.76rem;
    color: var(--ink-2);
  }
  .legend span { display: inline-flex; align-items: center; gap: 0.35rem; }
  .swatch {
    width: 14px; height: 3px; border-radius: 2px; display: inline-block;
  }
  .swatch.band { height: 11px; width: 11px; border-radius: 2px; opacity: 0.5; }

  .chart-scroll { overflow-x: auto; padding: 0.5rem 1.15rem 1.15rem; }
  svg { display: block; min-width: 520px; width: 100%; height: auto; }
  .grid-line { stroke: var(--rule); stroke-width: 1; }
  .axis-text {
    fill: var(--ink-3);
    font-family: var(--mono);
    font-size: 10px;
  }
  .series { fill: none; stroke-width: 2; stroke-linejoin: round; stroke-linecap: round; }
  .dot-miss { fill: var(--plate-red); }
  .deload-band { fill: var(--plate-yellow); opacity: 0.16; }
  .deload-edge { stroke: var(--plate-yellow); stroke-width: 1; stroke-dasharray: 3 3; }

  /* ---- timeline ---- */
  .sessions { display: flex; flex-direction: column; }
  .session {
    display: grid;
    grid-template-columns: 4px 5.5rem 1fr;
    gap: 0 0.9rem;
    align-items: start;
    padding: 0.7rem 1.15rem 0.7rem 0;
    border-top: 1px solid var(--rule);
  }
  .session:first-child { border-top: 0; }
  .stripe { align-self: stretch; border-radius: 0 2px 2px 0; background: transparent; }
  .session[data-state="miss"] .stripe { background: var(--plate-red); }
  .session[data-state="deload"] .stripe { background: var(--plate-yellow); }

  .when {
    font-family: var(--mono);
    font-size: 0.74rem;
    color: var(--ink-3);
    padding-left: 1.15rem;
    padding-top: 0.15rem;
    white-space: nowrap;
  }
  .when b { display: block; color: var(--ink-2); font-weight: 600; }

  .body { display: flex; flex-direction: column; gap: 0.4rem; min-width: 0; }
  .title-row {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 0.5rem;
  }
  .wname { font-size: 0.88rem; font-weight: 600; }
  .tag {
    font-family: var(--mono);
    font-size: 0.63rem;
    letter-spacing: 0.09em;
    text-transform: uppercase;
    padding: 0.12rem 0.42rem;
    border-radius: 3px;
    border: 1px solid currentColor;
  }
  .tag.deload { color: var(--plate-yellow); }
  .tag.miss { color: var(--plate-red); }

  .lifts { display: flex; flex-wrap: wrap; gap: 0.35rem; }
  .lift {
    display: inline-flex;
    align-items: baseline;
    gap: 0.4rem;
    background: var(--panel-2);
    border: 1px solid var(--rule);
    border-radius: 4px;
    padding: 0.2rem 0.5rem;
    font-size: 0.8rem;
  }
  .lift .nm { color: var(--ink-2); }
  .lift .ld {
    font-family: var(--mono);
    font-variant-numeric: tabular-nums;
    color: var(--ink);
    font-weight: 600;
  }
  .lift .amrap { color: var(--accent); font-family: var(--mono); font-size: 0.68rem; }

  /* ---- rules ---- */
  .rules { padding: 1.15rem; display: flex; flex-direction: column; gap: 0.9rem; }
  .rules h2 { margin-bottom: 0.15rem; }
  .rule-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(230px, 1fr));
    gap: 0.9rem;
  }
  .rule-card {
    border: 1px solid var(--rule);
    border-radius: 5px;
    padding: 0.75rem 0.85rem;
    background: var(--panel-2);
    display: flex;
    flex-direction: column;
    gap: 0.3rem;
  }
  .rule-card h3 {
    margin: 0;
    font-family: var(--mono);
    font-size: 0.68rem;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    color: var(--ink-3);
  }
  .rule-card p { margin: 0; font-size: 0.86rem; color: var(--ink-2); }
  .rule-card strong { color: var(--ink); font-variant-numeric: tabular-nums; }

  footer {
    font-size: 0.82rem;
    color: var(--ink-3);
    border-top: 1px solid var(--rule);
    padding-top: 1rem;
  }
  footer code {
    font-family: var(--mono);
    font-size: 0.78rem;
    background: var(--panel-2);
    border: 1px solid var(--rule);
    border-radius: 3px;
    padding: 0.05rem 0.3rem;
  }
  a { color: var(--accent); }

  @media (prefers-reduced-motion: no-preference) {
    .series { transition: opacity 0.15s ease; }
  }
  @media (max-width: 560px) {
    .session { grid-template-columns: 4px 1fr; }
    .when { grid-column: 2; padding-left: 0; }
    .body { grid-column: 2; }
  }
</style>

<div class="wrap">
  <header>
    <span class="eyebrow">Schlift · training programs</span>
    <h1>What the app will tell you to lift, and why</h1>
    <p class="lede">
      Every program in Schlift is a state machine: it proposes a session, watches
      what you actually do, and computes the next one. Pick a program and a
      situation to see the exact sequence it produces — including what happens
      when you stall, and when you disappear for six weeks.
    </p>
  </header>

  <section class="panel">
    <div class="controls">
      <div class="field">
        <label for="regime">Program</label>
        <select id="regime"></select>
      </div>
      <div class="field">
        <label for="seed">Starting point</label>
        <select id="seed"></select>
      </div>
      <div class="field">
        <label for="scenario">Situation</label>
        <select id="scenario"></select>
      </div>
    </div>
    <p class="scenario-note" id="scenario-note"></p>
  </section>

  <section class="panel">
    <div class="chart-head">
      <h2>Working weight over time</h2>
      <div class="legend" id="legend"></div>
    </div>
    <div class="chart-scroll"><svg id="chart" role="img" aria-label="Working weight per lift over the simulated period"></svg></div>
  </section>

  <section class="panel">
    <div class="chart-head"><h2>Session by session</h2></div>
    <div class="sessions" id="sessions"></div>
  </section>

  <section class="panel rules">
    <h2>The rules behind this</h2>
    <div class="rule-grid">
      <div class="rule-card">
        <h3>Time off</h3>
        <p>
          Under <strong>14 days</strong> between sessions, nothing changes. From
          <strong>14 days</strong> the next session is proposed at
          <strong>90%</strong>; from <strong>30 days</strong>, at
          <strong>80%</strong>. There is no further step past 30 days.
        </p>
      </div>
      <div class="rule-card">
        <h3>The deload sticks</h3>
        <p>
          Coming back lighter is only a proposal until you train. Once you
          complete a session, that reduced weight becomes your working weight and
          you build from there — you are not snapped back to your pre-break load.
        </p>
      </div>
      <div class="rule-card">
        <h3>Missing reps</h3>
        <p>
          A session counts as hit only if you complete at least as many working
          sets as prescribed. Falling short holds the weight and increments a
          stall counter; extra sets you add yourself never count against you.
        </p>
      </div>
      <div class="rule-card">
        <h3>Failing never raises the bar</h3>
        <p>
          A missed session can never make the next one heavier. Whatever you
          attempted, the next prescription is at most what you just failed.
        </p>
      </div>
      <div class="rule-card">
        <h3>Progress follows what you lifted</h3>
        <p>
          Change a weight mid-session and the program follows the weight you
          actually finished on, not the number it originally asked for. Reordering
          your exercises does not confuse it.
        </p>
      </div>
      <div class="rule-card">
        <h3>Three strikes</h3>
        <p>
          On Stronglifts 5&times;5, a third consecutive stall on a lift triggers a
          <strong>10%</strong> deload for that lift and resets the counter.
        </p>
      </div>
    </div>
  </section>

  <footer>
    <p>
      These timelines are produced by the app's own program engine — the Rust
      state machines are run forward and their output is rendered here, so this
      page cannot drift from what the app actually prescribes. Regenerate with
      <code>LIFT_SNAPSHOT_TIMELINE=1 cargo test regime_timeline</code> then
      <code>node scripts/build_regime_explorer.mjs</code>.
    </p>
    <p>
      Weights are shown in pounds and rounded to loadable increments. A
      <em>tier</em> label appears where a program distinguishes main work from
      volume or accessory work.
    </p>
  </footer>
</div>

<script>
const DATA = __PAYLOAD__;

const $ = (id) => document.getElementById(id);
const regimeSel = $('regime');
const seedSel = $('seed');
const scenarioSel = $('scenario');

const SERIES_COLORS = [
  'var(--plate-red)',
  'var(--plate-blue)',
  'var(--plate-green)',
  'var(--plate-yellow)',
  'var(--ink-2)',
  '#8a5bb5',
];

function fillSelect(sel, entries, keep) {
  sel.innerHTML = '';
  for (const [value, label] of entries) {
    const opt = document.createElement('option');
    opt.value = value;
    opt.textContent = label;
    sel.appendChild(opt);
  }
  if (keep && entries.some(([v]) => v === keep)) sel.value = keep;
}

function currentSessions() {
  const regime = DATA.regimes[regimeSel.value];
  const seed = regime.seeds[seedSel.value];
  return seed.scenarios[scenarioSel.value] ?? [];
}

/** Weight series per lift, taking the heaviest working set of each session. */
function seriesFrom(sessions) {
  const byLift = new Map();
  sessions.forEach((s, i) => {
    for (const ex of s.x) {
      const top = ex.s.reduce((m, set) => Math.max(m, set.w), 0);
      if (!byLift.has(ex.e)) byLift.set(ex.e, []);
      byLift.get(ex.e).push({ i, day: s.d, w: top, hit: s.hit });
    }
  });
  return [...byLift.entries()].map(([lift, points], idx) => ({
    lift,
    points,
    color: SERIES_COLORS[idx % SERIES_COLORS.length],
  }));
}

function renderChart(sessions) {
  const svg = $('chart');
  svg.innerHTML = '';
  if (!sessions.length) return;

  const series = seriesFrom(sessions);
  const W = 880, H = 300;
  const pad = { t: 12, r: 14, b: 30, l: 46 };
  svg.setAttribute('viewBox', '0 0 ' + W + ' ' + H);

  const maxDay = Math.max(...sessions.map((s) => s.d), 1);
  const weights = series.flatMap((s) => s.points.map((p) => p.w));
  const lo = Math.min(...weights), hi = Math.max(...weights);
  const padY = Math.max((hi - lo) * 0.12, 10);
  const yMin = Math.max(0, lo - padY), yMax = hi + padY;

  const x = (day) => pad.l + (day / maxDay) * (W - pad.l - pad.r);
  const y = (w) => H - pad.b - ((w - yMin) / (yMax - yMin || 1)) * (H - pad.t - pad.b);

  const ns = 'http://www.w3.org/2000/svg';
  const add = (tag, attrs, parent = svg) => {
    const el = document.createElementNS(ns, tag);
    for (const [k, v] of Object.entries(attrs)) el.setAttribute(k, v);
    parent.appendChild(el);
    return el;
  };

  // Deload periods: shade the gap that triggered them.
  sessions.forEach((s, i) => {
    if (!s.dl) return;
    const prevDay = i > 0 ? sessions[i - 1].d : 0;
    const x0 = x(prevDay), x1 = x(s.d);
    add('rect', { x: x0, y: pad.t, width: Math.max(x1 - x0, 2), height: H - pad.t - pad.b, class: 'deload-band' });
    add('line', { x1: x1, y1: pad.t, x2: x1, y2: H - pad.b, class: 'deload-edge' });
  });

  // Horizontal grid + y labels.
  const ticks = 5;
  for (let i = 0; i <= ticks; i++) {
    const val = yMin + ((yMax - yMin) * i) / ticks;
    const yy = y(val);
    add('line', { x1: pad.l, y1: yy, x2: W - pad.r, y2: yy, class: 'grid-line' });
    add('text', { x: pad.l - 8, y: yy + 3, 'text-anchor': 'end', class: 'axis-text' })
      .textContent = Math.round(val);
  }

  // X labels at first, middle and last session.
  for (const idx of [0, Math.floor(sessions.length / 2), sessions.length - 1]) {
    const s = sessions[idx];
    add('text', { x: x(s.d), y: H - pad.b + 16, 'text-anchor': 'middle', class: 'axis-text' })
      .textContent = 'day ' + s.d;
  }

  for (const s of series) {
    const d = s.points.map((p, i) => (i ? 'L' : 'M') + x(p.day) + ' ' + y(p.w)).join(' ');
    add('path', { d, class: 'series', stroke: s.color });
    // Mark missed sessions.
    for (const p of s.points) {
      if (!p.hit) add('circle', { cx: x(p.day), cy: y(p.w), r: 3, class: 'dot-miss' });
    }
    // Emphasise the endpoint.
    const last = s.points[s.points.length - 1];
    add('circle', { cx: x(last.day), cy: y(last.w), r: 3.5, fill: s.color });
  }

  const legend = $('legend');
  legend.innerHTML = '';
  for (const s of series) {
    const el = document.createElement('span');
    el.innerHTML = '<i class="swatch" style="background:' + s.color + '"></i>';
    el.append(s.lift);
    legend.appendChild(el);
  }
  const band = document.createElement('span');
  band.innerHTML = '<i class="swatch band" style="background:var(--plate-yellow)"></i>';
  band.append('time off → deload');
  legend.appendChild(band);
  const miss = document.createElement('span');
  miss.innerHTML = '<i class="swatch" style="background:var(--plate-red);height:8px;width:8px;border-radius:50%"></i>';
  miss.append('missed reps');
  legend.appendChild(miss);
}

function renderSessions(sessions) {
  const host = $('sessions');
  host.innerHTML = '';
  sessions.forEach((s) => {
    const row = document.createElement('div');
    row.className = 'session';
    row.dataset.state = s.dl ? 'deload' : s.hit ? 'ok' : 'miss';

    const stripe = document.createElement('div');
    stripe.className = 'stripe';

    const when = document.createElement('div');
    when.className = 'when';
    when.innerHTML = '<b>day ' + s.d + '</b>' + (s.g ? '+' + s.g + 'd' : 'start');

    const body = document.createElement('div');
    body.className = 'body';

    const titleRow = document.createElement('div');
    titleRow.className = 'title-row';
    const nm = document.createElement('span');
    nm.className = 'wname';
    nm.textContent = s.n;
    titleRow.appendChild(nm);
    if (s.dl) {
      const t = document.createElement('span');
      t.className = 'tag deload';
      t.textContent = 'deloaded after ' + s.g + ' days off';
      titleRow.appendChild(t);
    }
    if (!s.hit) {
      const t = document.createElement('span');
      t.className = 'tag miss';
      t.textContent = 'missed reps';
      titleRow.appendChild(t);
    }

    const lifts = document.createElement('div');
    lifts.className = 'lifts';
    for (const ex of s.x) {
      const chip = document.createElement('span');
      chip.className = 'lift';
      const load = ex.s
        .map((set) => set.c + '×' + set.r + (set.a ? '+' : '') + ' @ ' + set.w)
        .join(' · ');
      chip.innerHTML =
        '<span class="nm">' + ex.e + '</span><span class="ld">' + load + '</span>' +
        (ex.s.some((set) => set.a) ? '<span class="amrap">AMRAP</span>' : '');
      lifts.appendChild(chip);
    }

    body.append(titleRow, lifts);
    row.append(stripe, when, body);
    host.appendChild(row);
  });
}

function render() {
  const sessions = currentSessions();
  $('scenario-note').textContent =
    DATA.scenarioMeta[scenarioSel.value]?.blurb ?? '';
  renderChart(sessions);
  renderSessions(sessions);
}

function onRegimeChange() {
  const regime = DATA.regimes[regimeSel.value];
  const seedKeys = Object.keys(regime.seeds);
  fillSelect(seedSel, seedKeys.map((k) => [k, regime.seeds[k].label]), seedSel.value);
  onSeedChange();
}

function onSeedChange() {
  const regime = DATA.regimes[regimeSel.value];
  const seed = regime.seeds[seedSel.value] ?? Object.values(regime.seeds)[0];
  const keys = Object.keys(seed.scenarios).sort();
  fillSelect(
    scenarioSel,
    keys.map((k) => [k, DATA.scenarioMeta[k]?.label ?? k]),
    scenarioSel.value,
  );
  render();
}

fillSelect(
  regimeSel,
  Object.entries(DATA.regimes).map(([k, v]) => [k, v.name]),
);
regimeSel.addEventListener('change', onRegimeChange);
seedSel.addEventListener('change', onSeedChange);
scenarioSel.addEventListener('change', render);
onRegimeChange();
scenarioSel.value = 'comeback_after_layoff';
render();
</script>
`;

const out = html.replace('__PAYLOAD__', payload);
writeFileSync(join(root, 'docs/regime-explorer.html'), out);
console.log(
  `wrote docs/regime-explorer.html (${(out.length / 1024).toFixed(0)} KB, ` +
    `${Object.keys(data.regimes).length} programs)`,
);
